#!/usr/bin/env python3
"""
   Convert the MAME Fantasy (US) ROM set into Galagino Plus headers.
 
   MAME 0.288 romset is fantasyu.zip - "Fantasy (US)"

"""
from pathlib import Path
import io
import os
import sys
import wave
import zipfile
import zlib

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "pyconv"))
from romdata_emit import emit_compressed

HERE = Path(__file__).resolve().parent
ROOT = os.path.join(HERE, "..", "..", "..")
ARCHIVE = os.path.join(ROOT, "romszip", "fantasyu.zip")
OUT_DIR = os.path.join(ROOT, "source",  "src", "machines", "fantasy")
SAMPLE_ZIP = os.path.join(ROOT, "samples", "fantasy_samples.zip")
SAMPLE_NAMES = [f"ft_voi-{x:x}.wav" for x in range(12)]

MANIFEST = {
    "ic12.cpu":       (0x1000, 0x22CB2249),
    "ic07.cpu":       (0x1000, 0x0E2880B6),
    "ic08.cpu":       (0x1000, 0x4C331317),
    "ic09.cpu":       (0x1000, 0x6AC1DBFC),
    "ic10.cpu":       (0x1000, 0xC796A406),
    "ic14.cpu":       (0x1000, 0x6F1F0698),
    "ic15.cpu":       (0x1000, 0x5534D57E),
    "ic16.cpu":       (0x1000, 0x6C2AEB6E),
    "ic17.cpu":       (0x1000, 0xF6AA5DE1),
    "fs10ic50.bin":   (0x1000, 0x86A801C3),
    "fs11ic51.bin":   (0x1000, 0x9DFFF71C),
    "fantasy.ic7":    (0x0020, 0x361A5E99),
    "fantasy.ic6":    (0x0020, 0x33D974F7),
    "fs_b_51.bin":    (0x0800, 0x48094EC5),
    "fs_a_52.bin":    (0x0800, 0x1D0316E8),
    "fs_c_53.bin":    (0x0800, 0x49FD4AE8),
}

def load(archive: zipfile.ZipFile, name: str) -> bytes:
    try:
        data = archive.read(name)
    except KeyError:
        sys.exit(f"ERROR: missing {name} in {ARCHIVE}")
    size, expected_crc = MANIFEST[name]
    crc = zlib.crc32(data) & 0xffffffff
    if len(data) != size:
        sys.exit(f"ERROR: {name}: expected {size:#x} bytes, got {len(data):#x}")
    if crc != expected_crc:
        sys.exit(f"ERROR: {name}: CRC32 {crc:08X}, expected {expected_crc:08X}")
    return data

def write_header(filename: str, symbol: str, data: bytes, description: str, compress: bool = True) -> None:
    path = os.path.join(OUT_DIR, filename)
    with open(path, "w", newline="\n") as out:
        out.write("// Generated by romconv/fantasy/fantasy_rom_convert.py; do not edit.\n")
        out.write(f"// {description}\n")
        if compress:
            emit_compressed(out, symbol, "unsigned char", "", len(data), list(data))
        else:
            out.write(f"const unsigned char {symbol}[] = {{\n")
            for offset in range(0, len(data), 16):
                out.write("  " + ",".join(f"0x{x:02x}" for x in data[offset:offset + 16]) + ",\n")
            out.write("};\n")
    print(f"  wrote {path}: {len(data):#x} bytes")

def read_sample(archive: zipfile.ZipFile, name: str, target_rate: int = 6000) -> np.ndarray:
    try:
        raw = archive.read(name)
    except KeyError:
        sys.exit(f"ERROR: missing {name} in {SAMPLE_ZIP}")
    with wave.open(io.BytesIO(raw), "rb") as wav:
        channels, width, rate, frames = (wav.getnchannels(), wav.getsampwidth(),
                                         wav.getframerate(), wav.getnframes())
        pcm = wav.readframes(frames)
    if width == 1:
        values = np.frombuffer(pcm, dtype=np.uint8).astype(np.float32) - 128.0
    elif width == 2:
        values = np.frombuffer(pcm, dtype="<i2").astype(np.float32) / 256.0
    else:
        sys.exit(f"ERROR: {name}: only 8-bit or 16-bit PCM WAV is supported")
    if channels > 1:
        values = values.reshape(-1, channels).mean(axis=1)
    count = max(1, round(len(values) * target_rate / rate))
    converted = np.interp(np.arange(count, dtype=np.float32) * rate / target_rate,
                          np.arange(len(values)), values)
    return np.clip(np.rint(converted), -128, 127).astype(np.int8)

def ima_encode(pcm: np.ndarray) -> bytes:
    step_table = [7,8,9,10,11,12,13,14,16,17,19,21,23,25,28,31,34,37,41,45,
        50,55,60,66,73,80,88,97,107,118,130,143,157,173,190,209,230,253,
        279,307,337,371,408,449,494,544,598,658,724,796,876,963,1060,1166,
        1282,1411,1552,1707,1878,2066,2272,2499,2749,3024,3327,3660,4026,
        4428,4871,5358,5894,6484,7132,7845,8630,9493,10442,11487,12635,
        13899,15289,16818,18500,20350,22385,24623,27086,29794,32767]
    index_table = [-1,-1,-1,-1,2,4,6,8,-1,-1,-1,-1,2,4,6,8]
    predictor = int(pcm[0]) << 8
    first = predictor & 0xffff
    output = bytearray((first & 255, first >> 8))
    step_index, pending = 0, None
    for value in pcm[1:]:
        target, step = int(value) << 8, step_table[step_index]
        difference = target - predictor
        code = 8 if difference < 0 else 0
        difference = abs(difference)
        delta = step >> 3
        if difference >= step: code |= 4; difference -= step; delta += step
        if difference >= step >> 1: code |= 2; difference -= step >> 1; delta += step >> 1
        if difference >= step >> 2: code |= 1; delta += step >> 2
        predictor += -delta if code & 8 else delta
        predictor = max(-32768, min(32767, predictor))
        step_index = max(0, min(88, step_index + index_table[code]))
        if pending is None: pending = code
        else: output.append(pending | (code << 4)); pending = None
    if pending is not None:
        output.append(pending)
    return bytes(output)

def write_samples() -> None:
    if not os.path.isfile(SAMPLE_ZIP):
        sys.exit(f"ERROR: missing Fantasy sample pack: {SAMPLE_ZIP}")
    with zipfile.ZipFile(SAMPLE_ZIP) as archive:
        pcm_samples = [read_sample(archive, name) for name in SAMPLE_NAMES]
    samples = [ima_encode(pcm) for pcm in pcm_samples]
    offsets, lengths, position = [], [], 0
    for sample, pcm in zip(samples, pcm_samples):
        offsets.append(position); lengths.append(len(pcm)); position += len(sample)
    path = os.path.join(OUT_DIR, "fantasy_samples.h")
    with open(path, "w", newline="\n") as out:
        out.write("// Generated by romconv/fantasy/fantasy_rom_convert.py; do not edit.\n")
        out.write("// MAME Fantasy speech samples converted to mono 6 kHz 4-bit IMA-ADPCM.\n")
        out.write(f"#define FANTASY_SAMPLE_COUNT {len(samples)}\n")
        out.write("const uint32_t fantasy_sample_offsets[] = {\n  " +
                  ",".join(str(x) for x in offsets) + "\n};\n")
        out.write("const uint32_t fantasy_sample_lengths[] = {\n  " +
                  ",".join(str(x) for x in lengths) + "\n};\n")
        data = b"".join(samples)
        emit_compressed(out, "fantasy_samples", "unsigned char", "", len(data), list(data))
    print(f"  wrote {path}: {position:#x} ADPCM bytes")

def main() -> None:
    if not os.path.isfile(ARCHIVE):
        sys.exit(f"ERROR: missing ROM archive: {ARCHIVE}")
    os.makedirs(OUT_DIR, exist_ok=True)
    with zipfile.ZipFile(ARCHIVE) as archive:
        program = b"".join(load(archive, name) for name in (
            "ic12.cpu", "ic07.cpu", "ic08.cpu", "ic09.cpu", "ic10.cpu",
            "ic14.cpu", "ic15.cpu", "ic16.cpu", "ic17.cpu"))
        gfx = load(archive, "fs10ic50.bin") + load(archive, "fs11ic51.bin")
        proms = load(archive, "fantasy.ic7") + load(archive, "fantasy.ic6")
        sound = load(archive, "fs_b_51.bin") + load(archive, "fs_a_52.bin") + load(archive, "fs_c_53.bin")
    write_header("fantasy_rom.h", "fantasy_rom", program,
                 "Main M6502 ROMs mapped at 0x3000-0xbfff; IC14 is mirrored at 0xf000.")
    write_header("fantasy_gfx.h", "fantasy_gfx", gfx,
                 "Fixed graphics: 512 characters, 8x8, 2 bpp, separated bitplanes.")
    write_header("fantasy_proms.h", "fantasy_proms", proms,
                 "64-byte foreground/background palette PROMs.", compress=False)
    write_header("fantasy_sound_rom.h", "fantasy_sound_rom", sound,
                 "Three 2 KiB music data ROMs used by the SNK 6502 sound sequencer.")
    write_samples()
    print("Fantasy conversion complete.")

if __name__ == "__main__":
    main()
