#!/usr/bin/env python3
"""
roadfighter_rom_convert.py — converte Road Fighter (Konami 1984) in header C++
per il porting SPINNERINO (riuso infrastruttura Hyper Olympic).

Sorgente ROM: UNA SOLA -> roadf2.zip (set MAME standard "Road Fighter set 2").
  Contiene programma M6809 KONAMI-1 CIFRATO + GFX + audio + palette.
  Il programma decifrato (konami1_decrypt) == roadfu (set 3, verificato 0/49152 diff)
  = quello che gira. GFX/audio identici a roadf. Niente roadf.zip / roadfu.zip.
Driver MAME: konami/hyperspt.cpp  (roadf_state, main CPU = KONAMI-1 / M6809 cifrato)

Hardware (vedi MAME):
  CPU main : KONAMI-1 (M6809 con opcode cifrato) @ 18.432MHz/12 = 1.536 MHz
  CPU snd  : Z80 @ 14.318/4 = 3.58 MHz
  Audio    : SN76489A + DAC 8-bit R2R  (NIENTE VLM5030 su roadf)
  Display  : 256x256, visarea (0..255, 16..239), ROT90 portrait

Memory map main (roadf_state::main_map):
  $1000-$10BF sprite RAM    $10C0-$10FF scroll
  $1400 watchdog            $1480-$1487 output latch (flip/coin/sndena)
  $1500 sound latch         $1600 DSW2
  $1680 system in           $1681 P1   $1682 P2   $1683 DSW1
  $2000-$27FF VRAM          $2800-$2FFF CRAM
  $3000-$37FF work RAM      $3800-$3FFF NVRAM
  $4000-$FFFF ROM (48 KB)

ROM_START(roadf) — region maincpu (ROM mappata a $4000):
  g05_g01.bin 8K @0x4000   g07_f02.bin 8K @0x6000   g09_g03.bin 8K @0x8000
  g11_f04.bin 8K @0xA000   g13_f05.bin 8K @0xC000   g15_f06.bin 8K @0xE000
  region audiocpu:
  a17_d10.bin 8K @0x0000
  region sprites (0x8000):  j19_e14.bin 16K @0x0000   g19_e18.bin 16K @0x4000
  region tiles   (0xC000):  a14_e26.bin 16K @0x0000   a12_d24.bin  8K @0x4000
                            c14_e22.bin 16K @0x6000   c12_d20.bin  8K @0xA000
  region proms:
  c03_c27.bin  32B  palette PROM (32 colori)
  j12_c28.bin 256B  sprite color lookup (clut)
  a09_c29.bin 256B  char   color lookup (clut)

GFX layout SPECIFICO roadf (NON quello generico di Hyper Sports!):
  roadf_charlayout   : 8x8  4bpp, 1536 char, planes { 0x6000*8+4, 0x6000*8+0, 4, 0 }
  roadf_spritelayout : 16x16 4bpp, 256 spr, planes { 0x4000*8+4, 0x4000*8+0, 4, 0 }
  → la region tile e' divisa in 2 meta' da 0x6000 (plane bassi/alti),
    la region sprite in 2 meta' da 0x4000.

Palette decode (base_state::palette, hyperspt.cpp):
  Per i in 0..31 da c03_c27:
    R = pesi resistivi {1000,470,220} su bit 0,1,2
    G = pesi resistivi {1000,470,220} su bit 3,4,5
    B = pesi resistivi {470,220}      su bit 6,7
  Lookup (clut):
    sprite: pen = c28[i] & 0x0f          (palette entries 0..15)
    char  : pen = (c29[i] & 0x0f) | 0x10 (palette entries 16..31)

Output (in DAVIDE ORIGINALE/SPINNERINO/machines/roadfighter/, vedi OUT sotto):
  roadfighter_rom_main.h    48 KB  (_raw cifrato + _decrypted KONAMI-1; macchina usa dec in opcode-fetch)
  roadfighter_rom_audio.h    8 KB  Z80 sound
  roadfighter_gfx_tiles.h   48 KB  region tile grezza (2 meta' da 0x6000)
  roadfighter_gfx_sprites.h 32 KB  region sprite grezza (2 meta' da 0x4000)
  roadfighter_palette.h     32 colori RGB565 byte-swap + clut sprite[256] + clut char[256]
"""

import os
import sys
import zipfile
import hashlib

sys.path.insert(0, os.path.join("..", "pyconv"))
from romdata_emit import emit_compressed

ROM_SET = os.path.normpath(os.path.join("..", "..", "..", "romszip", "roadf2.zip"))
OUT_DIR = os.path.normpath(os.path.join("..", "..", "..", "source", "src", "machines", "roadfighter"))

def write_byte_array(path, var_name, data, typ="uint8_t"):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write(f"// Auto-generated by roadfighter_rom_convert.py\n")
        f.write(f"// {os.path.basename(path)}  size={len(data)} bytes\n")
        emit_compressed(f, var_name, "unsigned char", "", len(data), list(data))
    print(f"  wrote {path}  ({len(data)} bytes)")


def compute_weights(resistances, vmax=255):
    """Normalizzazione per conduttanza (compute_resistor_weights MAME, scala 0..vmax)."""
    cond = [1.0 / r for r in resistances]
    tot = sum(cond)
    return [c / tot * vmax for c in cond]


# KONAMI-1 opcode decryption (MAME konami.cpp mi_konami1::read_opcode).
# Solo l'OPCODE e' cifrato: XOR dipendente da A1,A3 dell'indirizzo.
#   addr&0xA == 0x0 -> ^0x22 (D1,D5)   0x2 -> ^0x82 (D1,D7)
#   addr&0xA == 0x8 -> ^0x28 (D3,D5)   0xA -> ^0x88 (D3,D7)
# I dati/operandi restano RAW. Non generiamo piu' un'ombra "decrypted" di
# tutta la ROM: un secondo array da 48KB sforava il budget di Arena
# (188416 > CAPACITY=182000, crash verificato all'avvio). La macchina
# decifra l'opcode al volo in m6809_read_opcode() con la stessa tabella.


# --- Boost colori (richiesto utente 2026-06-28): la palette PROM dell'arcade e'
# volutamente desaturata (rete resistori, 2 bit di blu) e su LCD moderno appare
# "smorta". Alziamo saturazione+luminosita' in HSV mantenendo la tinta. Livello
# "Leggero". Per disattivare: COLOR_SAT=1.0, COLOR_VAL=1.0. ---
import colorsys
COLOR_SAT = 1.3    # saturazione ("leggermente piu' carichi")
COLOR_VAL = 1.12   # luminosita'

def boost_rgb(r, g, b):
    h, s, v = colorsys.rgb_to_hsv(r/255.0, g/255.0, b/255.0)
    s = min(1.0, s * COLOR_SAT)
    v = min(1.0, v * COLOR_VAL)
    r2, g2, b2 = colorsys.hsv_to_rgb(h, s, v)
    return int(round(r2*255)), int(round(g2*255)), int(round(b2*255))


def build_palette(prom32):
    """32 colori da c03_c27 → RGB565 byte-swap (ESP32 SPI BE)."""
    rw = compute_weights([1000, 470, 220])   # R: bit0,1,2
    gw = compute_weights([1000, 470, 220])   # G: bit3,4,5
    bw = compute_weights([470, 220])         # B: bit6,7
    out = []
    for i in range(32):
        v = prom32[i]
        r = int(rw[0]*((v >> 0) & 1) + rw[1]*((v >> 1) & 1) + rw[2]*((v >> 2) & 1) + 0.5)
        g = int(gw[0]*((v >> 3) & 1) + gw[1]*((v >> 4) & 1) + gw[2]*((v >> 5) & 1) + 0.5)
        b = int(bw[0]*((v >> 6) & 1) + bw[1]*((v >> 7) & 1) + 0.5)
        r = min(255, r); g = min(255, g); b = min(255, b)
        r, g, b = boost_rgb(r, g, b)         # <-- boost colori (vedi sopra)
        rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        bs = ((rgb565 >> 8) & 0xFF) | ((rgb565 & 0xFF) << 8)
        out.append(bs)
    return out


# ---- GFX decode (roadf gfxlayout, KONAMI standard) ----
# char 8x8x4: planes {0x6000*8+4,0x6000*8+0,4,0}, xoffs {0,1,2,3,8*8..+3},
#             yoffs {0..7*8}, stride 16 byte. (2 plane bassi nel low half, 2 nel +0x6000)
# sprite 16x16x4: planes {0x4000*8+4,..}, xoffs {0,1,2,3,8*8..,16*8..,24*8..},
#             yoffs {0..7*8, 32*8..39*8}, stride 64 byte.
def decode_konami_tile(rom, T):
    half = 0x6000
    out = []
    for y in range(8):
        row = []
        for x in range(8):
            blo = T * 16 + y + (8 if x >= 4 else 0)
            bhi = half + blo
            xb = x & 3
            b0 = (rom[blo] >> (7 - xb)) & 1
            b1 = (rom[blo] >> (3 - xb)) & 1
            b2 = (rom[bhi] >> (7 - xb)) & 1
            b3 = (rom[bhi] >> (3 - xb)) & 1
            row.append((b3 << 3) | (b2 << 2) | (b1 << 1) | b0)
        out.append(row)
    return out

def decode_konami_sprite(rom, S):
    half = 0x4000
    out = []
    for y in range(16):
        yb = y if y < 8 else (24 + y)   # yoffs: y<8 -> y byte; y>=8 -> 32+(y-8) byte
        row = []
        for x in range(16):
            g = x >> 2
            xb = x & 3
            blo = S * 64 + yb + g * 8
            bhi = half + blo
            b0 = (rom[blo] >> (7 - xb)) & 1
            b1 = (rom[blo] >> (3 - xb)) & 1
            b2 = (rom[bhi] >> (7 - xb)) & 1
            b3 = (rom[bhi] >> (3 - xb)) & 1
            row.append((b3 << 3) | (b2 << 2) | (b1 << 1) | b0)
        out.append(row)
    return out

def pack8(px):
    """8 pixel 4-bit -> dword, pixel x al nibble x (px[0]=nibble0)."""
    val = 0
    for x in range(8):
        val = ((val >> 4) | (px[x] << 28)) & 0xFFFFFFFF
    return val

def write_tiles(path, tiles):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write("// Auto-generated by roadfighter_rom_convert.py\n")
        f.write(f"// {len(tiles)} tile 8x8x4 pre-decodificate (1 dword/riga, pixel x al nibble x)\n")
        f.write(f"#define ROADF_NTILES {len(tiles)}\n")
        flat = [pack8(t[y]) for t in tiles for y in range(8)]
        emit_compressed(f, "roadfighter_tiles", "uint32_t", "[8]", len(tiles), flat)
    print(f"  wrote {path}  ({len(tiles)} tiles)")

def write_sprites(path, sprites):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write("// Auto-generated by roadfighter_rom_convert.py\n")
        f.write(f"// {len(sprites)} sprite 16x16x4 pre-decodificati (2 dword/riga: x0-7, x8-15)\n")
        f.write(f"#define ROADF_NSPRITES {len(sprites)}\n")
        flat = []
        for s in sprites:
            for y in range(16):
                flat.append(pack8(s[y][0:8]))
                flat.append(pack8(s[y][8:16]))
        emit_compressed(f, "roadfighter_sprites", "uint32_t", "[32]", len(sprites), flat)
    print(f"  wrote {path}  ({len(sprites)} sprites)")


def write_palette(path, pal565, clut_spr, clut_chr):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write("// Auto-generated by roadfighter_rom_convert.py\n")
        f.write("// Road Fighter palette: 32 base colors + 2 color-lookup tables\n")
        f.write("#include <stdint.h>\n#include <pgmspace.h>\n\n")
        f.write("// 32 colori base RGB565 byte-swap\n")
        f.write(f"const unsigned short roadfighter_palette[32] PROGMEM = {{\n")
        for i in range(0, 32, 8):
            f.write("  " + ", ".join(f"0x{p:04X}" for p in pal565[i:i+8]) + ",\n")
        f.write("};\n\n")
        f.write("// clut sprite: pen = c28[i] & 0x0f  (indicizza palette[0..15])\n")
        f.write(f"const uint8_t roadfighter_clut_sprite[256] PROGMEM = {{\n")
        for i in range(0, 256, 16):
            f.write("  " + ", ".join(f"0x{b:02X}" for b in clut_spr[i:i+16]) + ",\n")
        f.write("};\n\n")
        f.write("// clut char: pen = (c29[i] & 0x0f) | 0x10  (indicizza palette[16..31])\n")
        f.write(f"const uint8_t roadfighter_clut_char[256] PROGMEM = {{\n")
        for i in range(0, 256, 16):
            f.write("  " + ", ".join(f"0x{b:02X}" for b in clut_chr[i:i+16]) + ",\n")
        f.write("};\n\n")
        # Colormap "bakate": colore RGB565 finale = palette[clut[color*16+pen]].
        # Indici: [color 0..15][pen 0..15]. Il render usa direttamente queste.
        f.write("// sprite colormap: palette[clut_sprite[color*16+pen]] (pen 0 = trasparente nel render)\n")
        f.write("const unsigned short roadfighter_sprite_colormap[16][16] PROGMEM = {\n")
        for c in range(16):
            r = [pal565[clut_spr[c * 16 + p]] for p in range(16)]
            f.write("  {" + ",".join(f"0x{v:04X}" for v in r) + "},\n")
        f.write("};\n\n")
        f.write("// tile colormap: palette[clut_char[color*16+pen]]\n")
        f.write("const unsigned short roadfighter_tile_colormap[16][16] PROGMEM = {\n")
        for c in range(16):
            r = [pal565[clut_chr[c * 16 + p]] for p in range(16)]
            f.write("  {" + ",".join(f"0x{v:04X}" for v in r) + "},\n")
        f.write("};\n")
    print(f"  wrote {path}  (32 colors + 2x256 clut + 2 colormap)")


def main():
    if not os.path.exists(ROM_SET):
        print(f"!! ZIP not found: {ROM_SET}", file=sys.stderr); sys.exit(1)
    print(f"[romconv_roadfighter] {ROM_SET}")
    zf = zipfile.ZipFile(ROM_SET)
    names = set(zf.namelist())

    needed = ["a17_d10.bin",
              "j19_e14.bin", "g19_e18.bin",
              "a14_e26.bin", "a12_d24.bin", "c14_e22.bin", "c12_d20.bin",
              "c03_c27.bin", "j12_c28.bin", "a09_c29.bin"]
    for n in needed:
        if n not in names:
            print(f"!! ROM mancante: {n}", file=sys.stderr); sys.exit(1)

    def rd(n, expect):
        d = zf.read(n)
        if len(d) != expect:
            print(f"!! size inattesa {n}: {len(d)} (atteso {expect})", file=sys.stderr); sys.exit(1)
        return d

    # --- main CPU ROM: 48 KB ($4000-$FFFF), 6 ROM da 8K cifrate KONAMI-1 ---
    # Da roadf2.zip (set 2): il programma decifrato == roadfu (set 3, quello che gira).
    #   5g -> $4000, 6g -> $6000, 8g -> $8000, 11g -> $A000,
    #   g13_f05 -> $C000, g15_f06 -> $E000.
    prog_files = ["5g", "6g", "8g", "11g", "g13_f05.bin", "g15_f06.bin"]
    for n in prog_files:
        if n not in names:
            print(f"!! ROM programma mancante in roadf.zip: {n}", file=sys.stderr); sys.exit(1)
    main_raw = b"".join(rd(n, 0x2000) for n in prog_files)
    if len(main_raw) != 0xC000:
        print(f"!! size programma inattesa {len(main_raw)} (atteso 0xC000)", file=sys.stderr); sys.exit(1)
    # KONAMI-1: opcode decifrato al volo dalla macchina (m6809_read_opcode),
    # non serve un'ombra "decrypted" precalcolata -- vedi commento sopra.
    write_byte_array(os.path.join(OUT_DIR, "roadfighter_rom_main.h"), "roadfighter_rom_main_raw", main_raw)

    # --- audio CPU ROM: 8 KB ---
    write_byte_array(os.path.join(OUT_DIR, "roadfighter_rom_audio.h"), "roadfighter_rom_audio", rd("a17_d10.bin", 0x2000))

    # --- tiles region 0xC000 (48 KB) -> 1536 tile 8x8x4 decodificate ---
    tiles_rom = bytearray(0xC000)
    tiles_rom[0x0000:0x4000] = rd("a14_e26.bin", 0x4000)
    tiles_rom[0x4000:0x6000] = rd("a12_d24.bin", 0x2000)
    tiles_rom[0x6000:0xA000] = rd("c14_e22.bin", 0x4000)
    tiles_rom[0xA000:0xC000] = rd("c12_d20.bin", 0x2000)
    tiles = [decode_konami_tile(tiles_rom, t) for t in range(1536)]
    write_tiles(os.path.join(OUT_DIR, "roadfighter_tiles.h"), tiles)

    # --- sprites region 0x8000 (32 KB) -> 256 sprite 16x16x4 decodificati ---
    spr_rom = bytearray(0x8000)
    spr_rom[0x0000:0x4000] = rd("j19_e14.bin", 0x4000)
    spr_rom[0x4000:0x8000] = rd("g19_e18.bin", 0x4000)
    sprites = [decode_konami_sprite(spr_rom, s) for s in range(256)]
    write_sprites(os.path.join(OUT_DIR, "roadfighter_sprites.h"), sprites)

    # --- palette + clut ---
    prom32 = rd("c03_c27.bin", 0x20)
    c28 = rd("j12_c28.bin", 0x100)
    c29 = rd("a09_c29.bin", 0x100)
    pal565 = build_palette(prom32)
    clut_spr = [c28[i] & 0x0f for i in range(256)]
    clut_chr = [(c29[i] & 0x0f) | 0x10 for i in range(256)]
    write_palette(os.path.join(OUT_DIR, "roadfighter_palette.h"), pal565, clut_spr, clut_chr)

    print("Done!")


if __name__ == '__main__':
    main()
