#!/usr/bin/env python3
"""Convert the MAME centiped3 (Centipede revision 3) ROM set into galagino headers."""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "pyconv"))
from gfxutil import load_file
from romdata_emit import emit_compressed

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..", "..", "..")
ARCHIVE = os.path.join(ROOT, "romszip", "centiped.zip")
OUT_DIR = os.path.join(ROOT, "source", "src", "machines", "centipede")

# MAME centiped3: name -> SHA1. PROM 136001-213.p4 is unused by the video
# hardware and dropped.
PROGRAM = [
    ("136001-307.d1", "8ea6e3304202831aabaf31dbd0f970a7b3bfe421"),
    ("136001-308.e1", "af4fdbf32c23b1864819d620a874e7f205da3cdb"),
    ("136001-309.fh1", "689fa560d40a384dcbcad7c8095bc12e91875580"),
    ("136001-310.j1", "c557db83876afc8ab52047ab1a3c3bfef34d6351"),
]
GFX = [
    ("136001-211.f7", "6c862352c329776f2f9974a0df9dbe41f9dbc361"),
    ("136001-212.hj7", "974c03d29aeca672fffa4dfc00a06be6a851aacb"),
]


def load_all(files):
    return b"".join(bytes(load_file(ARCHIVE, [name], sha1)) for name, sha1 in files)


def write(filename, symbol, data, description):
    path = os.path.join(OUT_DIR, filename)
    with open(path, "w", newline="\n") as out:
        out.write("// Generated by romconv/internal/centipede/centipede_rom_convert.py; do not edit.\n")
        out.write(f"// {description}\n")
        emit_compressed(out, symbol, "unsigned char", "", len(data), list(data))
    print(f"  wrote {path}: {len(data)} bytes")
    return len(data)


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    total = write("centipede_rom.h", "centipede_rom", load_all(PROGRAM),
                  "Main M6502 ROM, 8 KiB mapped at 0x2000-0x3fff.")
    total += write("centipede_gfx.h", "centipede_gfx", load_all(GFX),
                   "Tiles/sprites, 2 bpp planar: LSB plane 0x000-0x7ff, MSB plane 0x800-0xfff.")
    # the machine builds 2 KiB tile + 8 KiB sprite column tables from gfx in start()
    total += 2048 + 8192
    print(f"  Arena budget: {total} / 182000 bytes")
    if total >= 182000:
        sys.exit("ERROR: Arena budget exceeded")


if __name__ == "__main__":
    main()
