#!/usr/bin/env python3
"""Convert the MAME milliped (Millipede) ROM set into galagino headers."""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "pyconv"))
from gfxutil import load_file
from asset_emit import emit_compressed

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..", "..", "..")
ARCHIVE = os.path.join(ROOT, "romszip", "milliped.zip")
OUT_DIR = os.path.join(ROOT, "source", "src", "machines", "millipede")

# MAME milliped: name -> SHA1. Sync PROM 136001-213.e7 is not needed and
# dropped, as is the millipdd hack in the same archive.
PROGRAM = [
    ("136013-104.mn1", "b595d6a0f5d3c611ade1b83a94c3b909d2124dc4"),
    ("136013-103.l1", "9c1d0bbc20bf25dd21761a311fd1ed80aa029241"),
    ("136013-102.jk1", "9fe40db55ba1d20d4f11704f7f5df9ff75b87f30"),
    ("136013-101.h1", "ab06b1fd80271849946f90757b3837b617394929"),
]
GFX = [
    ("136013-107.r5", "4c7ea33d9501456ee8f5a642da7d6c972f2bb90d"),
    ("136013-106.p5", "602fcc7290f9f4eacb841c76665961ebf4307f80"),
]


def load_all(files):
    return b"".join(bytes(load_file(ARCHIVE, [name], sha1)) for name, sha1 in files)


def write(filename, symbol, data, description):
    path = os.path.join(OUT_DIR, filename)
    with open(path, "w", newline="\n") as out:
        out.write("// Generated by romconv/internal/millipede/millipede_rom_convert.py; do not edit.\n")
        out.write(f"// {description}\n")
        emit_compressed(out, symbol, "unsigned char", "", len(data), list(data))
    print(f"  wrote {path}: {len(data)} bytes")
    return len(data)


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    total = write("millipede_rom.h", "millipede_rom", load_all(PROGRAM),
                  "Main M6502 ROM, 16 KiB mapped at 0x4000-0x7fff.")
    total += write("millipede_gfx.h", "millipede_gfx", load_all(GFX),
                   "Tiles/sprites, 2 bpp planar: LSB plane 0x000-0x7ff, MSB plane 0x800-0xfff.")
    # the machine builds 2 KiB tile + 8 KiB sprite column tables from gfx in
    # start(), each allocated with 3 bytes alignment slack
    total += 2048 + 3 + 8192 + 3
    print(f"  Arena budget: {total} / 182000 bytes")
    if total >= 182000:
        sys.exit("ERROR: Arena budget exceeded")


if __name__ == "__main__":
    main()
