#!/usr/bin/env python3
"""
Recompress spaceinvaders_samples.h in place.

The original .wav -> PCM converter script this header was generated from
(convert_si_samples.py) is no longer present in the repo; only its checked-in
output is. This script treats that plain-array output as the source of truth
and re-emits it zlib-compressed (RomData<signed char, COMPRESSED>), without
touching the PCM sample values themselves.
"""

import os
import re
import sys

sys.path.insert(0, os.path.join("..", "pyconv"))
from romdata_emit import emit_compressed

OUT_DIR = os.path.normpath(os.path.join("..", "..", "..", "source", "src", "machines", "spaceinvaders"))
HEADER = os.path.join(OUT_DIR, "spaceinvaders_samples.h")

ARRAY_RE = re.compile(
    r"#define (\w+)_LEN (\d+)\s*"
    r"const signed char \1\[\] = \{(.*?)\};",
    re.DOTALL,
)

def main():
    with open(HEADER, "r") as f:
        src = f.read()

    arrays = []
    for m in ARRAY_RE.finditer(src):
        name, length, body = m.group(1), int(m.group(2)), m.group(3)
        values = [int(v) for v in body.replace("\n", " ").split(",") if v.strip()]
        assert len(values) == length, f"{name}: parsed {len(values)} values, expected {length}"
        arrays.append((name, values))

    if not arrays:
        print("  Already compressed (no plain array found), skipping.")
        return

    assert len(arrays) == 2, f"expected 2 sample arrays, found {len(arrays)}"

    with open(HEADER, "w") as f:
        f.write("// Space Invaders audio samples - 24kHz signed 8-bit PCM\n")
        f.write("// Auto-generated by romconv/invaders/samples_convert.py - DO NOT EDIT\n\n")
        for name, values in arrays:
            f.write(f"#define {name}_LEN {len(values)}\n")
            emit_compressed(f, name, "signed char", "", len(values), values)
            f.write("\n")

    for name, values in arrays:
        print(f"  Rewrote: {name} ({len(values)} bytes)")

if __name__ == "__main__":
    main()
