#!/usr/bin/env python3
"""Convert the MAME asteroid (Asteroids rev 4) ROM set into galagino headers."""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "pyconv"))
from gfxutil import load_file
from romdata_emit import emit_compressed

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..", "..", "..")
ARCHIVE = os.path.join(ROOT, "romszip", "asteroid.zip")
OUT_DIR = os.path.join(ROOT, "source", "src", "machines", "asteroids")

# MAME asteroid: name -> SHA1. The DVG state PROM 034602-01.c8 is dropped:
# the machine decodes the display list at a high level.
PROGRAM = [
    ("035145-04e.ef2", "5369dcfe01c0b9e48b15a96a0de8d23ee8ef9145"),
    ("035144-04e.h2", "51b2865fa897cdaa84ac6500c4b4833a80827019"),
    ("035143-02.j2", "1ce2eac1ab90b972e3f1fc3d250908f26328d6cb"),
]
VECTOR = [("035127-02.np3", "8cd5005e531eafa361d6b7e9eed159d164776c70")]

# asteroids::MAX_LINES vec2d::Line (16 B) + StripRasterizer next/active
# (2 x uint16_t per line) + 36 strip heads, allocated in start()
MAX_LINES = 1024
LINE_BUFFER_BYTES = MAX_LINES * 16 + MAX_LINES * 2 * 2 + 36 * 2


def load_all(files):
    return b"".join(bytes(load_file(ARCHIVE, [name], sha1)) for name, sha1 in files)


def write(filename, symbol, data, description):
    path = os.path.join(OUT_DIR, filename)
    with open(path, "w", newline="\n") as out:
        out.write("// Generated by romconv/internal/asteroids/asteroids_rom_convert.py; do not edit.\n")
        out.write(f"// {description}\n")
        emit_compressed(out, symbol, "unsigned char", "", len(data), list(data))
    print(f"  wrote {path}: {len(data)} bytes")
    return len(data)


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    total = write("asteroids_rom.h", "asteroids_rom", load_all(PROGRAM),
                  "Main M6502 ROM, 6 KiB mapped at 0x6800-0x7fff.")
    total += write("asteroids_vrom.h", "asteroids_vrom", load_all(VECTOR),
                   "DVG vector ROM, 2 KiB mapped at 0x5000-0x57ff.")
    total += LINE_BUFFER_BYTES
    print(f"  Arena budget: {total} / 182000 bytes")
    if total >= 182000:
        sys.exit("ERROR: Arena budget exceeded")


if __name__ == "__main__":
    main()
