#!/usr/bin/env python3
"""
   Convert the MAME Vanguard ROM set into Galagino Plus headers.

"""
from pathlib import Path
import io
import os
import sys
import wave
import zipfile
import zlib

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "pyconv"))
from romdata_emit import emit_compressed
from adpcm import ima_encode

HERE = Path(__file__).resolve().parent
ROOT = os.path.join(HERE, "..", "..")
ARCHIVE = os.path.join(ROOT, "romszip", "vanguard.zip")
OUT_DIR = os.path.join(ROOT, "source",  "src", "machines", "vanguard")
SAMPLE_ZIP = os.path.join(ROOT, "samples", "vanguard_samples.zip")
SAMPLE_NAMES = ["fire.wav", "explsion.wav"] + [f"vg_voi-{x:x}.wav" for x in range(16)]

# MAME `vanguard` parent set: filename -> (size, CRC32).
MANIFEST = {
    "sk4_ic07.bin": (0x1000, 0x6A29E354),
    "sk4_ic08.bin": (0x1000, 0x302BBA54),
    "sk4_ic09.bin": (0x1000, 0x424755F6),
    "sk4_ic10.bin": (0x1000, 0x54603274),
    "sk4_ic13.bin": (0x1000, 0xFDE157D0),
    "sk4_ic14.bin": (0x1000, 0x0D5B47D0),
    "sk4_ic15.bin": (0x1000, 0x8549B8F8),
    "sk4_ic16.bin": (0x1000, 0x062E0BE2),
    "sk5_ic50.bin": (0x0800, 0xE7D4315B),
    "sk5_ic51.bin": (0x0800, 0x96E87858),
    "sk5_ic7.bin":  (0x0020, 0xAD782A73),
    "sk5_ic6.bin":  (0x0020, 0x7DC9D450),
    "sk4_ic51.bin": (0x0800, 0xD2A64006),
    "sk4_ic52.bin": (0x0800, 0xCC4A0B6F),
}

def load(name: str) -> bytes:
    archive = zipfile.ZipFile(ARCHIVE)
    try:
        data = archive.read(name)
    except KeyError:
        sys.exit(f"ERROR: missing {name} in {ARCHIVE}")
    size, expected_crc = MANIFEST[name]
    crc = zlib.crc32(data) & 0xffffffff
    if len(data) != size:
        sys.exit(f"ERROR: {name}: expected {size:#x} bytes, got {len(data):#x}")
    if crc != expected_crc:
        sys.exit(f"ERROR: {name}: CRC32 {crc:08X}, expected {expected_crc:08X}")
    return data

def write_header(filename: str, symbol: str, data: bytes, description: str, compress: bool = True) -> None:
    path = os.path.join(OUT_DIR, filename)
    with open(path, "w", newline="\n") as out:
        out.write("// Generated by romconv/vanguard/vanguard_rom_convert.py; do not edit.\n")
        out.write(f"// {description}\n")
        if compress:
            emit_compressed(out, symbol, "unsigned char", "", len(data), list(data))
        else:
            out.write(f"const unsigned char {symbol}[] = {{\n")
            for offset in range(0, len(data), 16):
                out.write("  " + ",".join(f"0x{x:02x}" for x in data[offset:offset+16]) + ",\n")
            out.write("};\n")
    print(f"  wrote {path}: {len(data):#x} bytes")

def read_sample(archive: zipfile.ZipFile, name: str, target_rate: int) -> np.ndarray:
    try:
        raw = archive.read(name)
    except KeyError:
        sys.exit(f"ERROR: missing {name} in {SAMPLE_ZIP}")
    with wave.open(io.BytesIO(raw), "rb") as wav:
        channels, width, rate, frames = (wav.getnchannels(), wav.getsampwidth(),
                                         wav.getframerate(), wav.getnframes())
        pcm = wav.readframes(frames)
    if width == 1:
        values = np.frombuffer(pcm, dtype=np.uint8).astype(np.float32) - 128.0
    elif width == 2:
        values = np.frombuffer(pcm, dtype="<i2").astype(np.float32) / 256.0
    else:
        sys.exit(f"ERROR: {name}: only 8-bit or 16-bit PCM WAV is supported")
    if channels > 1:
        values = values.reshape(-1, channels).mean(axis=1)
    count = max(1, round(len(values) * target_rate / rate))
    positions = np.arange(count, dtype=np.float32) * rate / target_rate
    converted = np.interp(positions, np.arange(len(values)), values)
    return np.clip(np.rint(converted), -128, 127).astype(np.int8)

def write_samples() -> None:
    if not os.path.isfile(SAMPLE_ZIP):
        sys.exit(f"ERROR: missing Vanguard sample pack: {SAMPLE_ZIP}")
    with zipfile.ZipFile(SAMPLE_ZIP) as archive:
        rates = [8000, 8000] + [6000] * 16
        pcm_samples = [read_sample(archive, name, rate) for name, rate in zip(SAMPLE_NAMES, rates)]
        samples = [ima_encode(pcm) for pcm in pcm_samples]
    offsets, lengths, position = [], [], 0
    for sample, pcm in zip(samples, pcm_samples):
        offsets.append(position); lengths.append(len(pcm)); position += len(sample)
    path = os.path.join(OUT_DIR, "vanguard_samples.h")
    with open(path, "w", newline="\n") as out:
        out.write("// Generated by romconv/vanguard/vanguard_rom_convert.py; do not edit.\n")
        out.write("// MAME Vanguard samples converted to mono 4-bit IMA-ADPCM (effects 8 kHz, speech 6 kHz).\n")
        out.write(f"#define VANGUARD_SAMPLE_COUNT {len(samples)}\n")
        out.write("const uint32_t vanguard_sample_offsets[] = {\n  ")
        out.write(",".join(str(x) for x in offsets) + "\n};\n")
        out.write("const uint32_t vanguard_sample_lengths[] = {\n  ")
        out.write(",".join(str(x) for x in lengths) + "\n};\n")
        out.write("const unsigned char vanguard_sample_dividers[] = {\n  ")
        out.write(",".join(str(24000 // rate) for rate in rates) + "\n};\n")
        data = b"".join(samples)
        emit_compressed(out, "vanguard_samples", "unsigned char", "", len(data), list(data))
    print(f"  wrote {path}: {position:#x} ADPCM bytes")

def main() -> None:
    if not os.path.isfile(ARCHIVE):
        sys.exit(f"ERROR: missing ROM archive: {ARCHIVE}")
    os.makedirs(OUT_DIR, exist_ok=True)

    program = load("sk4_ic07.bin") + load("sk4_ic08.bin") + load("sk4_ic09.bin") + load("sk4_ic10.bin") +\
              load("sk4_ic13.bin") + load("sk4_ic14.bin") + load("sk4_ic15.bin") + load("sk4_ic16.bin")
    gfx = load("sk5_ic50.bin") + load("sk5_ic51.bin")
    proms = load("sk5_ic7.bin") + load("sk5_ic6.bin")
    sound = load("sk4_ic51.bin") + load("sk4_ic52.bin")
    write_header("vanguard_rom.h", "vanguard_rom", program,
                 "Main M6502 ROM: eight 4 KiB ROMs mapped at 0x4000-0xbfff; IC13 is mirrored at 0xf000.")
    write_header("vanguard_gfx.h", "vanguard_gfx", gfx,
                 "Fixed character graphics: 256 characters, 8x8, 2 bpp, separated bitplanes.")
    write_header("vanguard_proms.h", "vanguard_proms", proms,
                 "64-byte palette: foreground PROM followed by background PROM.", compress=False)
    write_header("vanguard_sound_rom.h", "vanguard_sound_rom", sound,
                 "Two 2 KiB music data ROMs used by the SNK 6502 sound sequencer.")
    write_samples()
    print("Vanguard conversion complete.")

if __name__ == "__main__":
    main()
