[platformio]
default_envs = cyd-2432s028r

[env]
platform = espressif32 @ 6.3.0
framework = arduino
;platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.9
monitor_speed = 115200
upload_speed = 1500000
extra_scripts = pre:extraScript.py
custom_prog_name = GALAGINO
custom_prog_version = v4.7.0
board_build.arduino.partitions = partitions.csv
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
build_unflags = -fno-rtti

build_flags =
    -D ARDUINO_RUNNING_CORE=0   ;default is 1
    -D BUILD_ENV_NAME=$PIOENV
    -O3
    -fopt-info
    -fverbose-asm
    -fdump-tree-switchconv

build_src_flags =
    -Wunknown-pragmas

[env:all_games]
build_flags =
  -D ENABLE_PACMAN
  -D ENABLE_GALAGA
  -D ENABLE_DKONG
  -D ENABLE_FROGGER
  -D ENABLE_DIGDUG
  -D ENABLE_1942
  -D ENABLE_EYES
  -D ENABLE_MRTNT
  -D ENABLE_LIZWIZ
  -D ENABLE_THEGLOB
  -D ENABLE_CRUSH
  -D ENABLE_ANTEATER
  -D ENABLE_BOMBJACK
  -D ENABLE_MRDO
  -D ENABLE_BAGMAN
  -D ENABLE_PENGO
  -D ENABLE_MSPACMAN
  -D ENABLE_GALAXIAN
  -D ENABLE_LADYBUG
  -D ENABLE_SPACEINVADERS
  -D ENABLE_TIMEPLT
  -D ENABLE_GYRUSS
  -D ENABLE_TUTANKHM
  -D ENABLE_DKONGJR
  -D ENABLE_STARFORCE
  -D ENABLE_MOONCRESTA
  -D ENABLE_SCRAMBLE
  -D ENABLE_SUPERCOBRA
  -D ENABLE_DKONG3
  -D ENABLE_POOYAN
  -D ENABLE_PHOENIX
  -D ENABLE_BURGERTIME
  -D ENABLE_XEVIOUS
  -D ENABLE_BNJ
  -D ENABLE_MAPPY
  -D ENABLE_GAPLUS
  -D ENABLE_ALIBABA
  -D ENABLE_AMIDAR
  -D ENABLE_TURTLES
  -D ENABLE_CIRCUSC
  -D ENABLE_ROCNROPE
  -D ENABLE_TODRUAGA
  -D ENABLE_VANVAN
  -D ENABLE_PBACTION
; -D ENABLE_MOTORACE
; -D ENABLE_ROADFIGHTER
  -D ENABLE_FANTASY
  -D ENABLE_NIBBLER
  -D ENABLE_SCREGG
  -D ENABLE_VANGUARD
  -D ENABLE_ZAXXON

[env:release_cheapYellowDisplay]
board = esp32-2432W328C
build_type = release
monitor_raw = yes
build_flags = ${env.build_flags}
    -D CHEAP_YELLOW_DISPLAY_CONF
    -D TFT_SPICLK=80000000
    -D CORE_DEBUG_LEVEL=0

[env:debug_cheapYellowDisplay]
board = esp32-2432W328C
build_type = debug
monitor_filters = esp32_exception_decoder
build_flags = ${env.build_flags}
    -D CHEAP_YELLOW_DISPLAY_CONF
    -D TFT_SPICLK=80000000

[env:release_azDeliveryDevKitV4]
board = az-delivery-devkit-v4
build_type = release
monitor_raw = yes
lib_deps =
    https://github.com/dmadison/NintendoExtensionCtrl
build_flags = ${env.build_flags}
    -D TFT_SPICLK=40000000
    -D CORE_DEBUG_LEVEL=0
    -D NUNCHUCK_INPUT

[env:debug_azDeliveryDevKitV4]
board = az-delivery-devkit-v4
build_type = debug
monitor_filters = esp32_exception_decoder
lib_deps =
    https://github.com/dmadison/NintendoExtensionCtrl
build_flags = ${env.build_flags}
    -D TFT_SPICLK=40000000
    -D NUNCHUCK_INPUT

[env:base-cyd]
board       = esp32dev
monitor_filters = time, esp32_exception_decoder
build_flags =
  ${env.build_flags}
  -D USE_PIO_CONFIG
  -D TFT_DC=2
  -D TFT_CS=15
  -D TFT_MISO=12
  -D TFT_MOSI=13
  -D TFT_SCLK=14
  -D TFT_BL=21
  -D TFT_BL_LEVEL=HIGH
  -D TFT_RST=-1
  -D GALAGINO_CONTROLLER
  -D GALAGINO_CONTROLLER_ADDR=0x09
  -D BTN_START_PIN=35
  -D BTN_LEFT_PIN=35
  -D BTN_RIGHT_PIN=35
  -D BTN_DOWN_PIN=35
  -D BTN_UP_PIN=35
  -D BTN_FIRE_PIN=35
lib_deps =
  ${env.lib_deps}

[env:cyd-2432s028r]
extends = env:base-cyd
build_flags =
  ${env:base-cyd.build_flags}
  -D TFT_ILI9341
  -D TFT_SPICLK=40000000L
  -D GALAGINO_CONTROLLER_SDA=27
  -D GALAGINO_CONTROLLER_SCL=22
  -D SILENT_ATTRACT_MODE
lib_deps =
  ${env:base-cyd.lib_deps}

;https://github.com/Freenove/Freenove_ESP32_Display
;https://docs.freenove.com/projects/fnk0103/en/latest/fnk0103/codes/tutorial/Freenove_ESP32_Display.html
; ILI9341 - SPI clock 40MHz
[env:cyd-fnk0103f]
extends = env:base-cyd
build_unflags =
  -fno-jump-tables
  -fno-tree-switch-conversion
build_flags =
  ${env:base-cyd.build_flags}
  ${env:all_games.build_flags}
  -O3
  -fopt-info
  -fverbose-asm
  -fjump-tables
  -ftree-switch-conversion
  -fdump-tree-switchconv
  -D AUDIO_ENABLE_PIN=4
  -D TFT_ILI9341
  -D TFT_SPI_HOST=SPI2_HOST
  -D TFT_SPICLK=40000000L
  -D GALAGINO_CONTROLLER_SDA=18
  -D GALAGINO_CONTROLLER_SCL=19
  -D SILENT_ATTRACT_MODE
; -D DEBUG_TIMING
lib_deps =
  ${env:base-cyd.lib_deps}

;https://github.com/Freenove/Freenove_ESP32_Display
;https://docs.freenove.com/projects/fnk0103/en/latest/fnk0103/codes/tutorial/Freenove_ESP32_Display.html
; ST7789 - SPI clock 80MHz
[env:cyd-fnk0103b]
extends = env:base-cyd
build_unflags =
  -fno-jump-tables
  -fno-tree-switch-conversion
build_flags =
  ${env:base-cyd.build_flags}
  ${env:all_games.build_flags}
  -O3
  -fopt-info
  -fverbose-asm
  -fjump-tables
  -ftree-switch-conversion
  -fdump-tree-switchconv
  -D AUDIO_ENABLE_PIN=4
  -D TFT_ST7789
  -D TFT_SPI_HOST=SPI2_HOST
  -D TFT_SPICLK=80000000L
  -D GALAGINO_CONTROLLER_SDA=18
  -D GALAGINO_CONTROLLER_SCL=19
  -D TFT_VFLIP
  -D SILENT_ATTRACT_MODE
; -D DEBUG_TIMING
lib_deps =
  ${env:base-cyd.lib_deps}

[env:cyd-2432s028r-usb-up]
extends = env:cyd-2432s028r
build_flags =
  ${env:cyd-2432s028r.build_flags}
  -D TFT_VFLIP
build_unflags =
  ${env:cyd-2432s028r.build_unflags}

[env:cyd-fnk0103f-usb-up]
extends = env:cyd-fnk0103f
build_flags =
  ${env:cyd-fnk0103f.build_flags}
  -D TFT_VFLIP
build_unflags =
  ${env:cyd-fnk0103f.build_unflags}

[env:cyd-fnk0103b-usb-up]
extends = env:cyd-fnk0103b
build_flags =
  ${env:cyd-fnk0103b.build_flags}
build_unflags =
  ${env:cyd-fnk0103b.build_unflags}
  -D TFT_VFLIP

; ILI9341 - SPI clock 40MHz
[env:cyd-esp32-s3-display-base]
board = fnk0104
monitor_filters = time, esp32_exception_decoder
build_flags =
  ${env.build_flags}
  ${env:all_games.build_flags}
  -D USE_PIO_CONFIG
  -D AUDIO_ENABLE_PIN=1
  -D TFT_CS=10
  -D TFT_DC=46
  -D TFT_MISO=13
  -D TFT_MOSI=11
  -D TFT_SCLK=12
  -D TFT_SPI_HOST=SPI2_HOST
  -D TFT_BL=45
  -D TFT_BL_LEVEL=HIGH
  -D TFT_RST=-1
  -D GALAGINO_CONTROLLER
  -D GALAGINO_CONTROLLER_ADDR=0x09
  -D ES8311_AUDIO
  -D ES8311_I2C_CLK=400000
  -D ES8311_I2C_ADDR=0x18
  -D ES8311_I2C_SDA=16
  -D ES8311_I2C_SCL=15
  -D ES8311_I2S_MCK=4
  -D ES8311_I2S_BCK=5
  -D ES8311_I2S_DIN=6
  -D ES8311_I2S_DOUT=8
  -D ES8311_I2S_WS=7
  -D BTN_START_PIN=35
  -D BTN_LEFT_PIN=35
  -D BTN_RIGHT_PIN=35
  -D BTN_DOWN_PIN=35
  -D BTN_UP_PIN=35
  -D BTN_FIRE_PIN=35
lib_deps =
  ${env.lib_deps}

[env:cyd-esp32-s3-display]
extends = env:cyd-esp32-s3-display-base
upload_speed = 2000000
board_build.boot = qio
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.arduino.partitions = partitions-s3-16M.csv
build_unflags =
  -fno-jump-tables
  -fno-tree-switch-conversion
build_flags =
  ${env:cyd-esp32-s3-display-base.build_flags}
  -O3
  -fopt-info
  -fopt-info-missed
  -fopt-info-inline-optimized-missed
  -fverbose-asm
  -fjump-tables
  -ftree-switch-conversion
  -fdump-tree-switchconv
  -D AUDIO_ENABLE_PIN=1
  -D TFT_ILI9341
  -D TFT_INVERT
  -D TFT_SPICLK=40000000L
  -D GALAGINO_CONTROLLER_SDA=16
  -D GALAGINO_CONTROLLER_SCL=15
;  -D SILENT_ATTRACT_MODE
lib_deps =
  ${env:cyd-esp32-s3-display-base.lib_deps}

[env:cyd-esp32-s3-display-usb-up]
extends = env:cyd-esp32-s3-display
board_build.boot = qio
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.arduino.partitions = partitions-s3-16M.csv
build_flags =
  ${env:cyd-esp32-s3-display.build_flags}
  -D TFT_VFLIP
  -D SILENT_ATTRACT_MODE
; -D DEBUG_TIMING
lib_deps =
  ${env:cyd-esp32-s3-display.lib_deps}


; host unit tests: devbox run -- bash -c "cd source && pio test -e native"
[env:native]
platform = native
framework =
extra_scripts =
build_unflags =
build_flags = -std=gnu++11 -pthread
build_src_flags =
lib_deps =
test_build_src = no
